### ISSUE TITLE
Update build instructions in README

### ISSUE THREAD

**Issue by Renegatto** [Unisay/purescript-lua-example#2]
There are no `build` script in the repo root. It is in `./scripts/`.

**Comment by Unisay** [comment]
There is the `.envrc` file which is used by the `direnv` tool to update your dev shell PATH, such that it includes `scripts` folder.
It won't work without `direnv` atm.

**Comment by Renegatto** [comment]
Okay, with `direnv` it works, but it doesn't seem sufficient as spago build fails:
```
purescript-lua-example$ build
Building...
[warn] Unable to parse compiler and package set versions, not checking if `purs` is compatible with it..
[info] Installing 1 dependencies.
[info] Searching for packages cache metadata..
[info] Recent packages cache metadata found, using it..
[info] Installing "lua-ngx"
[error] 
Failed to install dependency "lua-ngx"
Git output:

Cloning into '.'...
remote: Repository not found.
fatal: repository 'https://github.com/Unisay/purescript-lua-ngx.git/' not found


Aborting installation..
```
Is it private repo?

**Comment by Unisay** [comment]
I am afraid its not just ready yet. I need to finish reworking the compiler and then re-visit example project as well as the package set of libraries. This is a work in progress, stay tuned.

**Comment by Unisay** [comment]
This should work now, please give it a try!

**Comment by Unisay** [comment]
> Is it private repo?

It used to be, but I made it public.
