### ISSUE TITLE
Downloading and building GHC takes long time during first `nix develop`

### ISSUE THREAD

**Issue by Renegatto** [Unisay/purescript-lua-example#3]
Solution: suggest substitutes that has that GHC cached, so user may configure their nix in a way that GHC building step will be omited.

**Comment by Unisay** [comment]
Hey, thanks for the feedback!

Indeed, I've noticed that initial build takes a long time, but haven't had time to address it yet. 
I am working on finalizing inliner functionality, once its done I'd be back considering improvements for the example etc.

Btw, @Renegatto do you have an interest in PS -> Lua compilation? I didn't advertise this backend yet (at all) and was planning to do it once I have a bit more confidence in its completeness. It's 98% there, but I am still discovering bugs. Do you have interest in getting involved or you'd like to use it somehow? I am curious to learn about your interest.

Cheers!

**Comment by Renegatto** [comment]
Hey! I wanted to use this project to compile Purescript program to Lua, for minecraft ComputerCraft mode.
However, ended up writing own `base` and using `tstl`:

Purescript ->
JS ->
process with haskell scripts ->
tstl ->
incorrect lua ->
process with haskell scripts ->
correct lua

I really wish this project to get into usable state.

**Comment by Renegatto** [comment]
@Unisay if there are something that should be done to make it usable, I'd suggest to create tasks so people could contribute.

**Comment by Unisay** [comment]
> @Unisay if there are something that should be done to make it usable, I'd suggest to create tasks so people could contribute.

This is a valid point, thank you!

**Comment by Unisay** [comment]
I've added the [Cachix](https://docs.cachix.org/installation) binary nix cache:

```
cachix use purescript-lua
```
should configure your environment to use the cache, thus avoiding compiling a lot of dependencies.

> I really wish this project to get into usable state.

@Renegatto please give the project a try for your use-case, its in a early-usable state. I'd be happy to hear back about your results!
